name: gpt_box
description: "A third-party GPT Client for OpenAI API."
publish_to: 'none'
version: 1.0.385+385

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_links: ^6.1.1
  # audioplayers: ^6.0.0
  extended_image: ^9.0.0
  file_picker: ^8.0.0+1
  # flutter_js: ^0.8.1
  google_fonts: ^6.1.0
  html: ^0.15.4
  image: ^4.2.0
  image_picker: ^1.0.7
  screenshot: ^3.0.0
  shortid: ^0.1.2
  openai_dart: ^0.4.1
  json_annotation: ^4.9.0
  # flutter_riverpod: ^2.6.1
  # riverpod_annotation: ^2.6.1
  # dart_openai: #^5.1.0
  #   git:
  #     url: https://github.com/lollipopkit/dart_openai
  #     ref: a2f5f0dc8aea25530bbd38b3004f656b85e730b6
  webdav_client:
    git:
      ref: v1.0.66
      url: https://github.com/lollipopkit/webdav_client
  flutter_highlight: # ^0.7.0
    git:
      ref: master
      url: https://github.com/lollipopkit/highlight.dart
      path: flutter_highlight
  fl_lib:
    git:
      url: https://github.com/lppcg/fl_lib
      ref: v1.0.244

# dependency_overrides:
#   fl_lib:
#     path: ../fl_lib
  # fl_build:
  #   path: ../fl_build
  # flutter_highlight:
  #   path: ../highlight.dart/flutter_highlight

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.3.9
  json_serializable: ^6.8.0
  flutter_distributor: ^0.4.5
  # riverpod_generator: ^2.6.1
  # riverpod_lint: ^2.6.1
  fl_build:
    git:
      url: https://github.com/lppcg/fl_build.git
      ref: v1.0.48
    # path: ../fl_build

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
